### PR TITLE
Use modals for `creating`, `editing` & `deleting` reports

### PR DESCRIPTION
**Pull request by yhabteab**

### CODE REVIEW

**Review by TAINCER — COMMENTED** [review]
Code LGTM, but the URL stays the same after opening the modal. So if you would want to share the link to edit a report, you either have to know the URL or guess. I don't know if we have something like this already or if some sort of share button would be fitting.

**Comment by yhabteab** [comment]
🤷 

https://user-images.githubusercontent.com/57616252/219394692-2c4ae281-b45a-444c-a518-8d472477b7c5.mov

**Comment by TAINCER** [comment]
Nvm. then, I was just looking at the URL bar.

**Review by TAINCER — APPROVED** [review]
LGTM

**Pull request merged**
