### PR TITLE
Introduce and test permissions for reports and schedules

### PR DESCRIPTION
**Pull request by jnphilipp**

### CODE REVIEW

**Comment by lippserd** [comment]
Hi,

Thanks for the PR. We should take this one step further and introduce permissions instead of just testing for `reporting/*` because that is not really a real permission but just allows everything.

The permissions to introduce are:

* `reporting/reports` Allows the creation, modification and deletion of reports
* `reporting/schedules` Allows the creation, modification and deletion of schedules

Permissions are provided in the `configuration.php`, e.g.:

```php
$this->providePermission(
    'reporting/reports'
    $this->translate('Allow managing reports')
);

$this->providePermission(
    'reporting/schedules',
    $this->translate('Allow managing schedules')
);
```

Those permissions should be tested before creating the links.

But now we just don't display the links to administrative actions.
The URLs/actions itself are still accessible.

But there's `Controller::assertPermission()` to the rescue which stops execution if
the current user lacks the required permission, e.g.:

```php
class ReportController extends Controller
{
    ...

    public function editAction()
    {
        $this->assertPermission('reporting/reports');
        ...
    }

    ...
}
```

Regarding your current changes, please note that we  prefer no spaces in parentheses.

Do you want to work on those changes or should we take care of this?

All the best,
Eric

**Comment by jnphilipp** [comment]
Hi, no problem I can work on this.

For clarification: by default icingaweb2 has for every module permissions for full access and general access. The full access permissions are `reporting/*`. The two permissions you mentioned to be introduced are in addition to that? Which would mean that the testing would be still be for `reporting/*`.
Or are these default permissions removed if we add out own?.

**Comment by nilmerg** [comment]
Hi,

yes, the permissions Eric mentioned are in addition to the default `reporting/*` permission. They just allow more fine-grained control over what a user can access. The default permission will still be available even if we add more specific ones.

**Comment by jnphilipp** [comment]
Okay. Do I need to test for both or if I test for `reporting/reports` it includes `reporting/*`?

**Comment by nilmerg** [comment]
Just `reporting/reports` suffices. Anyone having granted `reporting/*` matches it as well.

**Comment by lippserd** [comment]
Hi,

Thanks for the changes. I made some modifications but could not push to your branch. So I created a new PR: #64 

All the best,
Eric

**Pull request closed without merging**
