### PR TITLE
Support PostgreSQL

### LINKED ISSUE #8: PostgreSQL support
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
We are a PostreSQL shop mainly and use it for any backing resources within Icinga2/Icinagweb2.  We would like to utilize this existing DB store to add the Reporting module, rather than go through the pain of adding and maintaining another DB store (MySQL).

## Describe alternatives you've considered
Setting up our own reporting solution with Hadoop Hive, but that does not solve integration or schema issues that we would need to solve ourselves. Plus, this has great integration and automation we would love to use.

## Additional context
None for now.

### PR DESCRIPTION
**Pull request by lippserd**
fixes #8

### CODE REVIEW

**Comment by mbanck** [comment]
AFAICT this PR needs updating for the template feature recently merged into master. The `templates` table has

```
settings longblob NOT NULL,
```

From looking at the code, the `settings` actually seems to be JSON, so maybe this could be handled transparently by using the `json` or `jsonb` data types in Postgres (note sure which version you target, but all currently upstream supported version have both, `jsonb` was added in 9.4).

**Comment by keithf4** [comment]
Just FYI, if this is plain json data, it may be better to use the `json` data type or even just plain `text`. Especially if all the json parsing is done in the application. The `json` type will validate that it is proper json, so that's a nice feature. If that's not needed, plain `text` would be fine. 

The jsonb is a special binary format that postgres uses to allow efficient parsing of json in the database itself and indexing. It will also de-dupe multiple similar keys. So it may not be consistent between differing database backends.

**Comment by lippserd** [comment]
@nbuchwitz Thanks for the missing bits. I'll give this one another test drive and will merge it afterwards.

**Comment by mtdeguzis** [comment]
Out of curiosity, update to this and tested it. Everything seems to work except the schedule run, and the standard debug/verbose options don't help. The icinga2 and icingaweb2 logs don't seem to show activity during the run. I won't dwell on it too much until this official, but I can try to help test as well.

My script module (runs on startup of a new instance) if that helps at all
```
# Enable module
icingacli module enable reporting

# Set resource elements
echo "Updating icingaweb2 host"
ini_set /etc/icingaweb2/resources.ini reporting host "\"${ICINGA_POSTGRES_CONTAINER}\""
echo "Updating icingaweb2 database password"
ini_set /etc/icingaweb2/resources.ini reporting password "\"${DB_REPORTING_PASSWORD}\""

# Create DB
if [[ $(psql -h ${DB_HOST} -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='reporting'")  = '1' ]]; then
    echo "Postgres database 'reporting' already exists"
else
    # reporting user
    if [[ $(psql -h ${DB_HOST} -U postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='reporting'")	= '1' ]]; then
        echo "DB User 'reporting' already exists"
    else
        echo "Creating DB user 'reporting'"
        if ! psql -h ${DB_HOST} -U ${DB_USER} -c "CREATE ROLE reporting WITH LOGIN PASSWORD '${DB_REPORTING_PASSWORD}'"; then
            echo "Failed to create Postgres user 'reporting'"
            exit 1
        fi
    fi

    # database
    echo "Creating Postgres DB 'reporting'"
    if ! createdb -h ${DB_HOST} -U ${DB_USER} -O reporting -E UTF8 reporting; then
        echo "Could not create Postgres database 'reporting'"
        exit 1
    else
        # Permissions
        echo "Granting 'reporting' user permission to reporting DB"
        if ! psql -h ${DB_HOST} -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE reporting TO reporting;"; then
            echo "ERROR: Failed to update permissions on reporting DB for user 'reporting'"
            exit 1
        fi
        
        echo "Granting table permissions to user 'reporting' in Database 'reporting'" 
        for table in $(psql -d reporting -h ${DB_HOST} -U postgres -c "\dt" | awk -F'| ' '{print $4}');
        do
            if ! psql -h ${DB_HOST} -d reporting -U postgres -c "GRANT ALL PRIVILEGES ON TABLE ${table} TO reporting;"; then
                echo "ERROR: Failed to grant permissions on ${table} table for user 'reporting'"
                #exit 1
            fi
        done

        echo "Importing schema into 'reporting' database"
        # Current schema set seems to have a syntax error: https://github.com/Icinga/icingaweb2-module-reporting/issues/1644
        # Seems like this needs to be done as the postgres user, as this interfaces with functions like
        # "unix_timestamp"
        if ! psql -h ${DB_HOST} -U ${DB_USER} -d reporting -f "/usr/share/icingaweb2/modules/reporting/schema/postgresql.sql"; then
            echo "Could not import reporting schema into 'reporting' database"
            exit 1
        fi

    fi
fi
```

* Icinga Web 2 version and modules (System - About): Icinga Web 2 Version 2.7.3, Git commit 06cabfe8ba28cf545a42c92f25484383191a4e51
* Web browser used: Chrome 80.0.3987.122
* Icinga 2 version used (icinga2 --version): 2.11.3-1
* PHP version used (php --version):
```
# /opt/rh/rh-php71/root/usr/sbin/php-fpm --version
PHP 7.1.30 (fpm-fcgi) (built: Nov  4 2019 10:09:22)
```
* Server operating system and version: CentOS 7.7

**Comment by lippserd** [comment]
@mtdeguzis Thanks for the tests. It may be obvious but did you define a schedule? 😆 If so, please share it and I'll have a look.

**Comment by mtdeguzis** [comment]
@lippserd  no I ran this manually:
```
icingacli reporting schedule run --verbose --debug
```
I assume a schedule would run the command underneath? I nabbed that from the installation doc to make sure a "first run" worked ok.

**Comment by lippserd** [comment]
Reports do have a schedule in order to run them automatically according to the schedule. You find it here:

10 211 55 9_icingaweb2_config_modules__dev=1

The command `icingacli reporting schedule run` is a daemon that executes the reports when they're "due".

**Comment by mtdeguzis** [comment]
That looks like IDO reports (sorry if I am derailing this thread)? I saw "If you are looking for SLA reports for your hosts and services, please also install the idoreports module." but I do not have that installed yet. Is ido-reports a dependency? 

Following https://github.com/Icinga/icingaweb2-module-reporting/blob/master/doc/02-Installation.md

**Comment by lippserd** [comment]
Could you open a new topic over at community.icinga.com with something like "Icinga Reporting with PostgreSQL". I'll help you there then. You may use your last post as entry point.

**Comment by mtdeguzis** [comment]
Got it thanks, https://community.icinga.com/t/icinga-reporting-with-postgresql-testing-issues/3950

**Comment by lippserd** [comment]
@bluthg @nbuchwitz Does it make sense to create the database with UTF-8? (I think so 😆)

```sql
CREATE DATABASE reporting
  WITH OWNER reporting
  ENCODING 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8';
```

**Comment by bluthg** [comment]
Absolutely. There really very few reasons that speak for anything else, none of them should apply to us...

**Comment by mbanck** [comment]
The `WITH OWNER reporting` looks unnecessary to me, I think the other icinga databases do not mandate a particular database owner?

**Comment by lippserd** [comment]
> The `WITH OWNER reporting` looks unnecessary to me, I think the other icinga databases do not mandate a particular database owner?
> 
> EDIT: oh I guess that was for/from the documentation, so disregard my comment.

I don't know what's common sense for the PostgreSQL folks to handle multiple database but for MySQL we always add a separate user/password for each database. I do think that makes sense for PostgreSQL as well, does it?

**Pull request merged**
