### PR TITLE
Add icon link to edit reports directly from the reports list

### PR DESCRIPTION
**Pull request by DamianoChini**
An edit link is needed directly in the reports table, so that it is possible to edit the settings of a report that either takes a long time to be generated or fails.

### CODE REVIEW

**Comment by lippserd** [comment]
Hi,

Thanks for the PR. Could you please either allow pushes to your branch or change the following:

* The commit message should read **Add icon link to edit reports directly from the reports list**
* The icon link should be a new last column. You don't need `float: right` then and please add `class: icon-col` to the new column

Either way, please always allow pushes from our side.

All the best,
Eric

**Comment by DamianoChini** [comment]
Hi,
Thanks for the feedback! I implemented the changes you suggested. 
I think by tomorrow you will also have permissions to push on the branch.

Damiano

**Comment by DamianoChini** [comment]
You should be able to push on the branch now

**Comment by lippserd** [comment]
> You should be able to push on the branch now

Nope, can't push unfortunately. I create a new PR though: #63

**Pull request closed without merging**
